default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: aiyashi_development

test:
  <<: *default
  database: aiyashi_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] || "aiyashi_production" %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] || "localhost" %>
